### ISSUE TITLE
backlight brightness

### ISSUE THREAD

**Issue by tdamsma** [anton-semeniak/Esphome-TTGO-T-Display-Weather#4]
In your example a brightness is configured:
```
display:
  - platform: st7789v
    id: st7789vdisplay
    reset_pin: GPIO23
    dc_pin: GPIO16
    cs_pin: GPIO5
    backlight_pin: GPIO4
    brightness: 25%
```

Changing this value doesn't seem to do anythng for me. Did you get that to work?

The backlight is pretty bright and I would like to be able to dim it, all I do now is just limit the luminosity of the colors I display, but that is a bit of a hack, especially considering the amount of light bleed from the lcd.
